#!/bin/bash

set -e

git fetch --prune
diff --new-line-format='' --unchanged-line-format='' <(git local-branches) <(git remote-branches | sed 's/^remotes\/origin\///') \
    | xargs git branch -d 2>&1 \
    | grep -v 'error: The branch' \
    | grep -v 'If you are sure you want to delete it'
