#!/bin/bash

set -e

echo 'Fetching remote branches'
git fetch --prune 2>/dev/null

remote_branches () {
    git branch -l -a | grep --color=never 'remotes/origin' | tr -d '* ' | grep -v HEAD | sed 's/remotes\/origin\///'
}
local_branches_with_tracking () {
    git remote show origin | grep 'merges with remote' | awk '{print $1}'
}

count=0
for branch in $(diff --new-line-format='' --unchanged-line-format='' <(local_branches_with_tracking) <(remote_branches)) ; do
    git branch -D $branch
    count=$(echo $((count + 1)))
done

echo "Deleted $count local branches"
